package model;

/**
 * This enum class represents all countries whose flags can be generated by this application.
 */
public enum Country {
  GREECE("greece"),
  SWITZERLAND("switzerland"),
  FRANCE("france");

  private String country;

  /**
   * Constructs the enum with the corresponding country name.
   *
   * @param country String representing the name of the country
   */
  Country(String country) {
    this.country = country;
  }

  @Override
  public String toString() {
    return this.country;
  }
}